### ISSUE TITLE
Shift and Jump quirks tests show both "ON" and "X" symbols

### ISSUE THREAD

**Issue by lbussell** [Timendus/chip8-test-suite#17]
Hi, first of all thanks for these incredibly helpful ROMs. My interpreter passes all of the logo, opcodes, flags, and input tests. However I noticed some weird behavior with the quirks rom. For the shift and jump quirks, my interpreter displays both the `ON` and `x` symbols, so I think something is wrong with my implementation but I'm not sure what, it's not very clear. I also referenced the Octo js code when trying to fix these quirks in my interpreter.

My interpreter's code for those quirks (in C#):

- Jump quirk: https://github.com/lbussell/CHIP-8/blob/02ac811390a83f7e34340f22d77f7584c888240a/src/Cpu.cs#L182-L185
- Shift quirk: https://github.com/lbussell/CHIP-8/blob/02ac811390a83f7e34340f22d77f7584c888240a/src/Cpu.cs#L146-L162

![image](https://github.com/Timendus/chip8-test-suite/assets/36081148/685d7a28-960e-4a65-99e8-0d5514eb3fcf)

Thanks for your time!

**Comment by lbussell** [comment]
Hmm, could it actually be showing that the quirk is supposed to be ON but it's not detecting if it's on?

**Comment by Timendus** [comment]
Hey there @lbussell, sorry for the late reply! I'm not on top of my Github notifications as much as I once was :)

Here's the idea:

The first column shows the quirk type. The second column shows if that quirk is currently detected as being `on` or `off` in your interpreter. The third column shows if that's actually correct given the platform you have selected.

So in your example, the shift and jump quirks are both detected as being `on`, even though they should be `off`. Which is why you have a cross there. Same for the display wait quirk, but the inverse; it's detected as `off` even though it should be `on`.
